name: wanikani_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Misc.
  logger: ^1.0.0
  meta: ^1.3.0
  crypto: ^3.0.1
  path_provider: ^2.0.2

  # Presentation
  shimmer_animation: ^2.1.0+1
  cupertino_icons: ^1.0.2
  auto_route: ^2.3.0
  flutter_riverpod: ^0.14.0+3

  # Dataclasses
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.2

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.0

  # Storage
  sembast: ^3.1.0+2
   
  # Networking 
  dio: ^4.0.0
  retrofit: ^2.0.1

  # Caching
  stash: 
    path: ../stash/packages/stash
  stash_sembast: 
    path: ../stash/packages/stash_sembast
  stash_dio: 
    path: ./packages/stash_dio
  stash_memory:
    path: ../stash/packages/stash_memory
  flutter_cache_manager: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: ^4.1.4
  test: ^1.16.8
  mockito: ^5.0.15
  http_mock_adapter: ^0.3.2
  pretty_dio_logger: ^1.2.0-beta-1
  injectable_generator: ^1.4.1
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/decoration/
    - assets/images/logos/
