name: wanikani_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^1.0.0
  retrofit: ^2.0.1
  json_annotation: ^4.0.1
  meta: ^1.3.0
  dio: ^4.0.0
  injectable: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: ^4.1.4
  test: ^1.16.8
  mockito: ^5.0.15
  http_mock_adapter: ^0.3.2
  pretty_dio_logger: ^1.2.0-beta-1
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true

  assets:
    - config.json
