name: stash_dio
version: 3.2.1
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_dio
publish_to: 'none'

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  http_parser: ^4.0.0
  crypto: ^3.0.1
  dio: ^4.0.0
  # stash: ^3.2.0
  stash:
   path: ../../../stash/packages/stash
  # stash_memory: ^3.2.0
  stash_memory:
   path: ../../../stash/packages/stash_memory
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
  mocktail: ^0.1.4
  stash_file: ^3.2.0
  #stash_file:
  #  path: ../stash_file
  dependency_validator: ^3.1.0
